# https://travis-ci.com/marmelab/15-puzzle-cli

sudo: required

language: python

python:
  - "3.5"

services:
  - docker

install:
  - make install

script:
  - make lint
  - make test

branches:
  only:
    - master
